### PR TITLE
Allow intermediary recorded times to have the same value

### PR DESCRIPTION
**Pull request by ana-cc**

### CODE REVIEW

**Comment by robgjansen** [comment]
I'm having a hard time understanding the implications of this commit on the json output. Do you have a quick example of the difference in the json output before this commit compared to after? Otherwise, I'd like to run a test to check it.

**Comment by ana-cc** [comment]
To sum up, where we send/receive a very small number of bytes, "before" might look like:

              "payload_progress_send": {
                "0.0": 6.510206,
                "0.1": 6.912496,
                "0.2": 6.933803,
                "0.3": 6.965237,
                "0.4": 6.999372,
                "0.5": 6.999907,
                "0.6": 7.000328,
                "0.7": 7.033762,
                "0.8": 7.063519,
                "0.9": 7.090643,
                "1.0": 7.091094
              }
...after the merge request, it would look like:

              "payload_progress_send": {
                "0.0": 6.510206,
                "0.1": 6.510206,
                "0.2": 6.510206,
                "0.3": 6.510206,
                "0.4": 6.510206,
                "0.5": 6.510206,
                "0.6": 6.510206,
                "0.7": 6.510206,
                "0.8": 6.510206,
                "0.9": 6.510206,
                "1.0": 6.510206
              }
The output **would only change for very small number of bytes**. In this example we send 1Kb, and in the tgen log output, this means `payload-progress-send` is already at 100% immediately after stream authentication,  like in the following log:


```
2020-06-11 15:51:34 1591887094.465468 [info] [tgen-stream.c:595] [_tgenstream_readAuthenticate] stream authentication successful!
2020-06-11 15:51:34 1591887094.465506 [info] [tgen-stream.c:375] [_tgenstream_changeRecvState] stream [id=3,vertexid=stream5m,name=ana-X550JK,peername=(null),sendsize=1024,recvsize=5242880,sendstate=SEND_SUCCESS,recvstate=RECV_AUTHENTICATE,error=NONE] moving from recv state RECV_AUTHENTICATE to recv state RECV_HEADER
2020-06-11 15:51:34 1591887094.465565 [info] [tgen-stream.c:375] [_tgenstream_changeRecvState] stream [id=3,vertexid=stream5m,name=ana-X550JK,peername=ana-X550JK,sendsize=1024,recvsize=5242880,sendstate=SEND_SUCCESS,recvstate=RECV_HEADER,error=NONE] moving from recv state RECV_HEADER to recv state RECV_PAYLOAD
2020-06-11 15:51:34 1591887094.513015 [info] [tgen-stream.c:1649] [_tgenstream_log] [stream-status] transport [fd=9,local=localhost:127.0.0.1:41418,proxy=localhost:127.0.0.1:56117,remote=jzxfvaupigl7hkemf4jhfi2vrruvbb7ucyiwdolkkc2hf3xlm34f3qyd.onion:0.0.0.0:8080,state=SUCCESS_OPEN,error=NONE] stream [id=3,vertexid=stream5m,name=ana-X550JK,peername=ana-X550JK,sendsize=1024,recvsize=5242880,sendstate=SEND_SUCCESS,recvstate=RECV_PAYLOAD,error=NONE] bytes [total-bytes-recv=3557,total-bytes-send=3237,payload-bytes-recv=3486,payload-bytes-send=1024,payload-progress-recv=0.07%,payload-progress-send=100.00%]
2020-06-11 15:51:34 1591887094.522722 [info] [tgen-stream.c:1649] [_tgenstream_log] [stream-status] transport [fd=9,local=localhost:127.0.0.1:41418,proxy=localhost:127.0.0.1:56117,remote=jzxfvaupigl7hkemf4jhfi2vrruvbb7ucyiwdolkkc2hf3xlm34f3qyd.onion:0.0.0.0:8080,state=SUCCESS_OPEN,error=NONE] stream [id=3,vertexid=stream5m,name=ana-X550JK,peername=ana-X550JK,sendsize=1024,recvsize=5242880,sendstate=SEND_SUCCESS,recvstate=RECV_PAYLOAD,error=NONE] bytes [total-bytes-recv=4553,total-bytes-send=3237,payload-bytes-recv=4482,payload-bytes-send=1024,payload-progress-recv=0.09%,payload-progress-send=100.00%]
2020-06-11 15:51:34 1591887094.525706 [info] [tgen-stream.c:1649] [_tgenstream_log] [stream-status] transport [fd=9,local=localhost:127.0.0.1:41418,proxy=localhost:127.0.0.1:56117,remote=jzxfvaupigl7hkemf4jhfi2vrruvbb7ucyiwdolkkc2hf3xlm34f3qyd.onion:0.0.0.0:8080,state=SUCCESS_OPEN,error=NONE] stream [id=3,vertexid=stream5m,name=ana-X550JK,peername=ana-X550JK,sendsize=1024,recvsize=5242880,sendstate=SEND_SUCCESS,recvstate=RECV_PAYLOAD,error=NONE] bytes [total-bytes-recv=9035,total-bytes-send=3237,payload-bytes-recv=8964,payload-bytes-send=1024,payload-progress-recv=0.17%,payload-progress-send=100.00%]
2020-06-11 15:51:34 1591887094.538014 [info] [tgen-stream.c:1649] [_tgenstream_log] [stream-status] transport [fd=9,local=localhost:127.0.0.1:41418,proxy=localhost:127.0.0.1:56117,remote=jzxfvaupigl7hkemf4jhfi2vrruvbb7ucyiwdolkkc2hf3xlm34f3qyd.onion:0.0.0.0:8080,state=SUCCESS_OPEN,error=NONE] stream [id=3,vertexid=stream5m,name=ana-X550JK,peername=ana-X550JK,sendsize=1024,recvsize=5242880,sendstate=SEND_SUCCESS,recvstate=RECV_PAYLOAD,error=NONE] bytes [total-bytes-recv=11525,total-bytes-send=3237,payload-bytes-recv=11454,payload-bytes-send=1024,payload-progress-recv=0.22%,payload-progress-send=100.00%]
```
We could improve on the solution in this merge request if we return only the largest (in this case 1.0) value in case the timestamps are identical.

**Comment by ana-cc** [comment]
Also attaching before/after analysis files:
[before.gz](https://github.com/shadow/tgen/files/4956996/before.gz)
[after.gz](https://github.com/shadow/tgen/files/4956997/after.gz)

**Comment by robgjansen** [comment]
Ahh, I see now! Thank you for the detailed explanation!

**Pull request merged**
